ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

CREATE USER Desarrollo IDENTIFIED BY Cibertec
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
PROFILE DEFAULT;

GRANT CONNECT, RESOURCE TO Desarrollo;
GRANT CREATE ANY TABLE TO Desarrollo;
GRANT CREATE SEQUENCE TO Desarrollo;

GRANT CREATE SYNONYM TO desarrollo;
GRANT CREATE PUBLIC SYNONYM TO desarrollo;

ALTER USER Desarrollo QUOTA 10M ON USERS;


